### ISSUE TITLE
Error while connecting to Web socket.

### ISSUE THREAD

**Issue by DhavalRKansara** [shamblett/mqtt_client#149]
Hello @shamblett,
I have established a connection successfully with my broker through TCP. But now they have added a certificate for the secure connection and for that using WebSocket I am not able to establish a connection with the broker.

- **Code for connection through WebSocket:**

```
final MqttClient client = MqttClient('wss://aaa.bbb.ccc', '');

Future setUpMQTT() async {
    client.logging(on: true);
    client.onConnected = onConnected;
    client.keepAlivePeriod = 30;
    client.onSubscribed = onSubscribed;
    client.onDisconnected = onDisconnected;
    client.onUnsubscribed = onUnsubscribed;
    client.pongCallback = pong;
    client.useWebSocket = true;
    client.port = xxxx;
    client.websocketProtocols = MqttWsConnection.protocolsSingleDefault;

    final MqttConnectMessage connMess = MqttConnectMessage()
        .withClientIdentifier(
            'xxxxxxxx-yyyyyyyy-zzzzzzzz')
        .authenticateAs('username', 'password')
        .keepAliveFor(30)
        .startClean()
        .withWillQos(MqttQos.atMostOnce);

    print(' Mosquitto client connecting....');

    client.connectionMessage = connMess;

    ///Connection
    try {
      await client.connect('username','password');
    } on Exception catch (e) {
      print('client Connection exception - $e');
    }
  }


```
- **I am getting below error:**

```
flutter:  Mosquitto client connecting....
flutter: 2020-01-20 15:52:56.709101 -- Authenticating with username '{websocketuser}' and password '{wbcGH+2qTEe.78U}'
flutter: 2020-01-20 15:52:56.709238 -- Username length (13) exceeds the max recommended in the MQTT spec.
flutter: 2020-01-20 15:52:56.709351 -- Password length (15) exceeds the max recommended in the MQTT spec.
flutter: 2020-01-20 15:52:56.719281 -- SynchronousMqttConnectionHandler::internalConnect entered
flutter: 2020-01-20 15:52:56.719448 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
flutter: 2020-01-20 15:52:56.719616 -- SynchronousMqttConnectionHandler::internalConnect - websocket selected
flutter: 2020-01-20 15:52:56.727883 -- MqttWsConnection:: WS URL is wss:/aaa.bbb.ccc:xxxx, protocols are [mqtt]
flutter: 2020-01-20 15:52:58.182711 -- MqttConnection::_onError - calling disconnected callback
flutter: client Connection exception - WebSocketException: Connection to 'https://aaa.bbb.ccc:xxxx#' was not upgraded to websocket

```

**Comment by shamblett** [comment]
On this line 

```
MqttWsConnection:: WS URL is wss:/aaa.bbb.ccc:xxxx, protocols are [mqtt]
```
it says your protocol string is mqtt, some brokers don't like this, see the API docs on how to set this to null or to a string of your choice.

**Comment by DhavalRKansara** [comment]
> On this line
> 
> ```
> MqttWsConnection:: WS URL is wss:/aaa.bbb.ccc:xxxx, protocols are [mqtt]
> ```
> 
> it says your protocol string is mqtt, some brokers don't like this, see the API docs on how to set this to null or to a string of your choice.


Didn't get you @shamblett.
`MqttWsConnection:: WS URL is wss:/aaa.bbb.ccc:xxxx, protocols are [mqtt]` 

It's  just a log right? and After commenting 
`client.websocketProtocols = MqttWsConnection.protocolsSingleDefault;` from code I am getting below logs:
```
flutter:  Mosquitto client connecting....
flutter: 2020-01-20 16:19:35.640884 -- Authenticating with username '{websocketuser}' and password '{wbcGH+2qTEe.78U}'
flutter: 2020-01-20 16:19:35.641032 -- Username length (13) exceeds the max recommended in the MQTT spec.
flutter: 2020-01-20 16:19:35.641146 -- Password length (15) exceeds the max recommended in the MQTT spec.
flutter: 2020-01-20 16:19:35.651676 -- SynchronousMqttConnectionHandler::internalConnect entered
flutter: 2020-01-20 16:19:35.651838 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
flutter: 2020-01-20 16:19:35.652016 -- SynchronousMqttConnectionHandler::internalConnect - websocket selected
flutter: 2020-01-20 16:19:35.660348 -- MqttWsConnection:: WS URL is wss://aaa.bbb.ccc:xxxx, protocols are [mqtt, mqttv3.1, mqttv3.11]
flutter: 2020-01-20 16:19:37.075650 -- MqttConnection::_onError - calling disconnected callback
flutter: client Connection exception - WebSocketException: Connection to 'https://aaa.bbb.ccc:xxxx#' was not upgraded to websocket


```

**Comment by shamblett** [comment]
Yes sorry what I meant was disable the protocol string entirely,
```
client.websocketProtocols = [];
```

**Comment by DhavalRKansara** [comment]
> Yes sorry what I meant was disable the protocol string entirely,
> 
> ```
> client.websocketProtocols = [];
> ```

- **After these changes:**
```
flutter: 2020-01-20 17:26:16.692711 -- SynchronousMqttConnectionHandler::internalConnect entered
flutter: 2020-01-20 17:26:16.692886 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
flutter: 2020-01-20 17:26:16.693065 -- SynchronousMqttConnectionHandler::internalConnect - websocket selected
flutter: 2020-01-20 17:26:16.701155 -- MqttWsConnection:: WS URL is wss://aaa.bbb.ccc:xxxx, protocols are []
flutter: 2020-01-20 17:26:17.864209 -- MqttConnection::_onError - calling disconnected callback
flutter: client Connection exception - WebSocketException: Connection to 'https://aaa.bbb.ccc:xxxx#' was not upgraded to websocket


```

**Comment by shamblett** [comment]
OK, another thing to try is to set 'useAlternateWebSocketImplementation' to true, this sometimes works with AWS based brokers, otherwise you may have to look at your broker logs to see if it can shed any light on whats happening.

**Comment by DhavalRKansara** [comment]
> OK, another thing to try is to set 'useAlternateWebSocketImplementation' to true, this sometimes works with AWS based brokers, otherwise you may have to look at your broker logs to see if it can shed any light on whats happening.

@shamblett Thanks for quick replies.

- I added the above parameter  in code and getting the following error:
```
flutter: 2020-01-20 18:40:09.041508 -- SynchronousMqttConnectionHandler::internalConnect entered
flutter: 2020-01-20 18:40:09.041729 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
flutter: 2020-01-20 18:40:09.041910 -- SynchronousMqttConnectionHandler::internalConnect - alternate websocket implementation selected
flutter: 2020-01-20 18:40:09.043250 -- MqttWs2Connection::connect
flutter: 2020-01-20 18:40:09.050805 -- MqttWs2Connection:: WS URL is wss://aaa.bbb.ccc:xxxx, protocols are []
flutter: 2020-01-20 18:40:09.767342 -- MqttWs2Connection::connect - securing socket
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: mqtt-client::NoConnectionException: MqttWs2Connection::TLS connection unexpectedly closed
#0      MqttWs2Connection._performWSHandshake.<anonymous closure> (package:mqtt_client/src/connectionhandling/mqtt_client_mqtt_ws2_connection.dart:214:7)
#1      _rootRun (dart:async/zone.dart:1120:38)
#2      _CustomZone.run (dart:async/zone.dart:1021:19)
#3      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#7      _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:772:19)
#8      _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#9      _StreamController.close (dart:async/stream_controller.dart:622:5)
#10     _Socket._onData (dart:io-patch/socket_p<…>
```

**Comment by DhavalRKansara** [comment]
Is there any public broker available by which I can establish a demo for WebSocket connection using this library?

**Comment by shamblett** [comment]
OK this gives us a bit more info 

```
MqttWs2Connection::TLS connection unexpectedly closed
```
so it appears there's something wrong at the TLS level, unfortunately Dart does not help you much here especially with websockets, unlike secure TCP sockets where you supply a security context you don't do this, you just use wss and Dart does the rest. 

You could try Mosquito, also the client is known to work with the AWS broker over websockets.

**Comment by DhavalRKansara** [comment]
For Mosquito, I have tried  `test.mosquitto.org` with port `8081` from this link and I have established connection successfully. Below is the code: 

```
final MqttClient client = MqttClient('wss://test.mosquitto.org', '');

Future setUpMQTT() async {
    client.logging(on: true);
    client.onConnected = onConnected;
    client.keepAlivePeriod = 30;
    client.onSubscribed = onSubscribed;
    client.onDisconnected = onDisconnected;
    client.onUnsubscribed = onUnsubscribed;
    client.pongCallback = pong;
    client.useWebSocket = true;
    client.port = 8081;

    final MqttConnectMessage connMess = MqttConnectMessage()
        .withClientIdentifier(
            'clientId-sxuuJMiVPH')
        .authenticateAs('', '')
        .keepAliveFor(30)
        .startClean()
        .withWillQos(MqttQos.atMostOnce);

    print(' Mosquitto client connecting....');

    client.connectionMessage = connMess;

    ///Connection
    try {
      await client.connect('','');
    } on Exception catch (e) {
      print('client Connection exception - $e');
    }
  }

```

- So I have discussed this with my broker and I'll get back to you with some logs from their side. So we can debug further on these issues.

**Comment by DhavalRKansara** [comment]
Hello @shamblett 

I have tried to establish a connection with my broker over [here](https://www.eclipse.org/paho/clients/js/utility/) and the connection was established successfully. Please find the below screenshot.
![Screen Shot 2020-01-21 at 4 12 08 PM](https://user-images.githubusercontent.com/44993081/72799631-aecc1900-3c6b-11ea-9d99-8ba3e333d4a2.png)

But while I am trying to connect through this library still getting error.

- **Code for Connection:**

 ```
 Future setUpMQTT() async {
  final MqttClient client = MqttClient('wss://mqttws.ray.life', '');
    client.logging(on: true);
    client.onConnected = onConnected;
    client.keepAlivePeriod = 30;
    client.onSubscribed = onSubscribed;
    client.onDisconnected = onDisconnected;
    client.onUnsubscribed = onUnsubscribed;
    client.pongCallback = pong;
    client.useWebSocket = true;
    client.port = 38100;
    client.websocketProtocols = [];
    client.useAlternateWebSocketImplementation = true;

    final MqttConnectMessage connMess = MqttConnectMessage()
        .withClientIdentifier('js-utility-Dz8p1')
        .authenticateAs('websocketuser', 'anypassword')
         .keepAliveFor(30)
        .startClean()
        .withWillQos(MqttQos.atMostOnce);
    print(' Mosquitto client connecting....');

    client.connectionMessage = connMess;

    ///Connection
    try {
      await client.connect();
    } on Exception catch (e) {
      print('client Connection exception - $e');
    }
  }
```

- **Error:**


```
flutter:  Mosquitto client connecting....
flutter: 2020-01-21 16:41:01.226190 -- SynchronousMqttConnectionHandler::internalConnect entered
flutter: 2020-01-21 16:41:01.226423 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
flutter: 2020-01-21 16:41:01.226607 -- SynchronousMqttConnectionHandler::internalConnect - alternate websocket implementation selected
flutter: 2020-01-21 16:41:01.228226 -- MqttWs2Connection::connect
flutter: 2020-01-21 16:41:01.236526 -- MqttWs2Connection:: WS URL is wss://mqttws.ray.life:38100, protocols are []
flutter: 2020-01-21 16:41:02.122658 -- MqttWs2Connection::connect - securing socket
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: mqtt-client::NoConnectionException: MqttWs2Connection::TLS connection unexpectedly closed
#0      MqttWs2Connection._performWSHandshake.<anonymous closure> (package:mqtt_client/src/connectionhandling/mqtt_client_mqtt_ws2_connection.dart:214:7)
#1      _rootRun (dart:async/zone.dart:1120:38)
#2      _CustomZone.run (dart:async/zone.dart:1021:19)
#3      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#4      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:389:13)
#5      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:399:15)
#6      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:283:7)
#7      _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:772:19)
#8      _StreamController._closeUnchecked (dart:async/stream_controller.dart:629:7)
#9      _StreamController.close (dart:async/stream_controller.dart:622:5)
#10     _Socket._onData (dart:io-patch/socket_p<…>
```

**Comment by shamblett** [comment]
OK, the only other thing I can think of is to remove the '.withWillQos(MqttQos.atMostOnce);', we've had problems in this area before, also the timeout on Paho is 60, not 30, not that this should make any difference. At the end of the day its the Dart runtime that does the TLS stuff, not the mqtt_client, you really need the server logs to see why it thinks something is wrong. Also swap back to not using the alternate ws implementation, i.e. 'client.useAlternateWebSocketImplementation = false' or don't specify it.

**Comment by DhavalRKansara** [comment]
> OK, the only other thing I can think of is to remove the '.withWillQos(MqttQos.atMostOnce);', we've had problems in this area before, also the timeout on Paho is 60, not 30, not that this should make any difference. At the end of the day its the Dart runtime that does the TLS stuff, not the mqtt_client, you really need the server logs to see why it thinks something is wrong. Also swap back to not using the alternate ws implementation, i.e. 'client.useAlternateWebSocketImplementation = false' or don't specify it.

Okay... I tried to remove `withWillQos(MqttQos.atMostOnce);` and added other options of MqttQos too. Also, I changed the timeout from 30 to 60 but there weren't any changes in the logs. 

After removing    `client.useAlternateWebSocketImplementation = true;` logs are:

```
flutter:  Mosquitto client connecting....
flutter: 2020-01-21 17:15:55.800107 -- SynchronousMqttConnectionHandler::internalConnect entered
flutter: 2020-01-21 17:15:55.800331 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
flutter: 2020-01-21 17:15:55.800688 -- SynchronousMqttConnectionHandler::internalConnect - websocket selected
flutter: 2020-01-21 17:15:55.810562 -- MqttWsConnection:: WS URL is wss://mqttws.ray.life:38100, protocols are []
flutter: 2020-01-21 17:17:43.746436 -- MqttConnection::_onError - calling disconnected callback
flutter: client Connection exception - WebSocketException: Connection to 'https://mqttws.ray.life:38100#' was not upgraded to websocket
```

**Comment by DhavalRKansara** [comment]
@shamblett  Is there any solution available for the above issues?

**Comment by shamblett** [comment]
Your going to need your broker logs to find out what's going on here, especially as you say above that it works OK with the mosquito broker. Who's broker are you using?
