### ISSUE TITLE
Stopping server causes traceback

### ISSUE THREAD

**Issue by gokr** [shamblett/mqtt_client#17]
Stopping mosquitto server causes the following, I guess we should do better (I am still Dart noob).

```
StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:io/io_sink.dart:160)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:165)
#2      _Socket.add (dart:io-patch/socket_patch.dart:1565)
#3      MqttConnection.send (package:mqtt_client/src/connectionhandling/mqtt_client_mqtt_connection.dart:109:12)
#4      MqttConnectionHandler.sendMessage (package:mqtt_client/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:73:18)
#5      MqttConnectionKeepAlive.pingRequired (package:mqtt_client/src/connectionhandling/mqtt_client_mqtt_connection_keep_alive.dart:52:26)
#6      Timer._createTimer.<anonymous closure> (dart:async-patch/dart:async/timer_patch.dart:21)
#7      _Timer._runTimers (dart:isolate-patch/dart:isolate/timer_impl.dart:382)
#8      _Timer._handleMessage (dart:isolate-patch/dart:isolate/timer_impl.dart:416)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by shamblett** [comment]
Yep, we should, I'll have a look at this.

**Comment by shamblett** [comment]
Could you try this test again on the latest client
