### ISSUE TITLE
Unhandled exception: SocketException: MqttConnection::On Done called by broker, disconnecting.

### ISSUE THREAD

**Issue by yolkhovyy** [shamblett/mqtt_client#2]
Evaluating the mqtt_client, getting an exception in connect():

Authenticating with username '...' and password '...'
Username length (14) exceeds the max recommended in the MQTT spec. 
Password length (18) exceeds the max recommended in the MQTT spec. 
2017-10-31 04:05:17.525056 -- MqttConnectPayload::Client id exceeds spec value of 23
2017-10-31 04:05:17.571400 -- SynchronousMqttConnectionHandler::internalConnect entered
2017-10-31 04:05:17.572771 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
2017-10-31 04:05:17.574705 -- SynchronousMqttConnectionHandler::internalConnect - insecure TCP selected
2017-10-31 04:05:17.739883 -- MqttConnection::_startListening
2017-10-31 04:05:17.756835 -- SynchronousMqttConnectionHandler::internalConnect sending connect message
2017-10-31 04:05:17.776349 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
Connect Variable Header: ProtocolName=MQTT, ProtocolVersion=4, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=false, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=true, UserNameFlag=true, KeepAlive=60
Instance of 'MqttConnectPayload'

2017-10-31 04:05:17.876106 -- SynchronousMqttConnectionHandler::internalConnect - pre sleep, state = ConnectionState.connecting
**Unhandled exception:
SocketException: MqttConnection::On Done called by broker, disconnecting.**
#0      MqttConnection._onDone (package:mqtt_client/src/connectionhandling/mqtt_client_mqtt_connection.dart:88:7)
#1      _RootZone.runGuarded (dart:async/zone.dart:1296)
#2      _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:384)
#3      _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:394)
#4      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:277)
#5      _StreamController&&_SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:804)
#6      _StreamController._closeUnchecked (dart:async/stream_controller.dart:656)
#7      _StreamController.close (dart:async/stream_controller.dart:649)
#8      _Socket._onData (dart:io-patch/socket_patch.dart:1624)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#12     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#13     _StreamController._add (dart:async/stream_controller.dart:667)
#14     _StreamController.add (dart:async/stream_controller.dart:613)
#15     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1210)
#16     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:753)
#17     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#18     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#19     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#20     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
../../runtime/vm/dart_api_impl.cc: 1878: error: Dart_GetMainPortId expects there to be a current isolate. Did you forget to call Dart_CreateIsolate or Dart_EnterIsolate?
Aborted

**Comment by shamblett** [comment]
Looks as though the broker is closing the connection because of something it doesn't like in the connect message, the MQTT spec lists a number of things that can cause this, check your broker logs if you have access to them.  The username and password length warnings look wrong for the lengths you are using, I'll look at this. Which broker a re you using?

**Comment by yolkhovyy** [comment]
It's the Bluemix broker of IBM. The name/password sizes are defined by the IoT Watson platform of IBM - can't get around that.

The Bluemix broker works fine with the name/password if I use this lib: https://github.com/jnguillerme/mqtt.dart. The lib does not support secure sockets - the reason I'm looking at yours.

I will try your examples with Bluemix and my settings. Will keep you updated.

**Comment by shamblett** [comment]
I've opened a bluemix trial account, I get the following on connect to my test device 

Authenticating with username '{use-token-auth}' and password '{.....}'
Username length (14) exceeds the max recommended in the MQTT spec. 
Password length (18) exceeds the max recommended in the MQTT spec. 
2017-11-01 08:21:54.301613 -- MqttConnectPayload::Client id exceeds spec value of 23
2017-11-01 08:21:54.308094 -- SynchronousMqttConnectionHandler::internalConnect entered
2017-11-01 08:21:54.308155 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
2017-11-01 08:21:54.308298 -- SynchronousMqttConnectionHandler::internalConnect - insecure TCP selected
2017-11-01 08:21:54.341810 -- MqttConnection::_startListening
2017-11-01 08:21:54.348286 -- SynchronousMqttConnectionHandler::internalConnect sending connect message
2017-11-01 08:21:54.350308 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=false, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=true, UserNameFlag=true, KeepAlive=60
Instance of 'MqttConnectPayload'
2017-11-01 08:21:54.364631 -- SynchronousMqttConnectionHandler::internalConnect - pre sleep, state = ConnectionState.connecting
2017-11-01 08:21:54.373388 -- MqttConnection::_onData
2017-11-01 08:21:54.378817 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.connectAck
Header: MessageType = MqttMessageType.connectAck, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
Connect Variable Header: TopicNameCompressionResponse={0}, ReturnCode={MqttConnectReturnCode.notAuthorized}

As you can see I'm getting a not authorised connect response, don't know why this is as I'm no bluemix expert but I am getting a response, you don't seem to be. Have a look at the test mqtt_client_broker_test_publish.dart, I edited this to produce the above

**Comment by yolkhovyy** [comment]
Take a look at this: https://developer.ibm.com/answers/questions/405505/my-devices-get-connection-refused-not-authorised-w/

By default you should use secure connection. You can disable this somewhere in your Bluemix settings.

I've tried the iot_core.dart example with my settings - the same result as in my first post here.

**Comment by shamblett** [comment]
OK, I've set my test client to use secure and left Bluemix on TLS with token auth so we are using TLS, it now connects 3 times and each time gets a connect ack of not authorised, no TLS handshake error.  I'll look further, the iot-core example needs the google root certs installed on your machine if you do not have them. Whic version of Dart are you using BTW and on what host OS?

**Comment by yolkhovyy** [comment]
Ubuntu 16.04
Dart 1.24.2

I used your iot_core example, replaced all google by Bluemix, unsecure connection. The example as is (google api) works fine in my setup.

**Comment by yolkhovyy** [comment]
Commented out this line:
client.setProtocolV311();

and everything looks much better:

Authenticating with username '{use-token-auth}' and password '{.....}'
Username length (14) exceeds the max recommended in the MQTT spec.
Password length (18) exceeds the max recommended in the MQTT spec.
2017-11-02 21:07:15.203144 -- MqttConnectPayload::Client id exceeds spec value of 23
2017-11-02 21:07:15.208131 -- SynchronousMqttConnectionHandler::internalConnect entered
2017-11-02 21:07:15.208239 -- SynchronousMqttConnectionHandler::internalConnect - initiating connection try 0
2017-11-02 21:07:15.208367 -- SynchronousMqttConnectionHandler::internalConnect - insecure TCP selected
2017-11-02 21:07:15.285327 -- MqttConnection::_startListening
2017-11-02 21:07:15.292179 -- SynchronousMqttConnectionHandler::internalConnect sending connect message
2017-11-02 21:07:15.294346 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=false, WillQos=MqttQos.atLeastOnce, WillRetain=false, PasswordFlag=true, UserNameFlag=true, KeepAlive=60
Instance of 'MqttConnectPayload'

2017-11-02 21:07:15.311428 -- SynchronousMqttConnectionHandler::internalConnect - pre sleep, state = ConnectionState.connecting
2017-11-02 21:07:15.348656 -- MqttConnection::_onData
2017-11-02 21:07:15.352929 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.connectAck
Header: MessageType = MqttMessageType.connectAck, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
Connect Variable Header: TopicNameCompressionResponse={0}, ReturnCode={MqttConnectReturnCode.connectionAccepted}

2017-11-02 21:07:15.355356 -- MqttConnection::_onData - message processed
2017-11-02 21:07:15.361936 -- SynchronousMqttConnectionHandler::_connectAckProcessor
2017-11-02 21:07:15.362102 -- SynchronousMqttConnectionHandler::_connectAckProcessor - state = connected
2017-11-02 21:07:20.313219 -- SynchronousMqttConnectionHandler::internalConnect - post sleep, state = ConnectionState.connected
2017-11-02 21:07:20.313309 -- SynchronousMqttConnectionHandler::internalConnect exited with state ConnectionState.connected
iotcore client connected
2017-11-02 21:07:20.316606 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.publish
Header: MessageType = MqttMessageType.publish, Duplicate = false, Retain = false, Qos = MqttQos.exactlyOnce, Size = 0
Publish Variable Header: TopicName={iot-2/type/OpenGHGateway/id/oghgwspike/evt/PubEnvData/fmt/json}, MessageIdentifier={1}, VH Length={0}
Payload: {4 bytes={<97><98><99><100>

Sleeping....
2017-11-02 21:07:20.390766 -- MqttConnection::_onData
2017-11-02 21:07:20.391839 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.publishReceived
Header: MessageType = MqttMessageType.publishReceived, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
PublishReceived Variable Header: MessageIdentifier={1}

2017-11-02 21:07:20.391933 -- MqttConnection::_onData - message processed
2017-11-02 21:07:20.392845 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.publishRelease
Header: MessageType = MqttMessageType.publishRelease, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
PublishRelease Variable Header: MessageIdentifier={1}

2017-11-02 21:07:20.413324 -- MqttConnection::_onData
2017-11-02 21:07:20.414184 -- MqttConnection::_onData - message received MQTTMessage of type MqttMessageType.publishComplete
Header: MessageType = MqttMessageType.publishComplete, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 2
PublishComplete Variable Header: MessageIdentifier={1}

2017-11-02 21:07:20.414299 -- MqttConnection::_onData - message processed
Disconnecting
2017-11-02 21:07:30.318775 -- SynchronousMqttConnectionHandler::disconnect
2017-11-02 21:07:30.338152 -- MqttConnectionHandler::sendMessage - MQTTMessage of type MqttMessageType.disconnect
Header: MessageType = MqttMessageType.disconnect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0

2017-11-02 21:07:30.338255 -- MqttConnectionHandler::sendMessage - not connected

**Comment by yolkhovyy** [comment]
My app also works now with mqtt_client.
Will experiment further with secure connection to Amazon AWS IoT - will let you know the result.

Thanks a lot for your work!

**Comment by shamblett** [comment]
Glad its working, I'll leave this issue open for any feedback you may have, also please suggest any improvements/fixes/ etc. to the mqtt_client API itself, there's no better feedback than from people using it.

**Comment by shamblett** [comment]
Ok, nothing else heard, closing
