### ISSUE TITLE
Unable to connect to an own Mosquitto broker

### ISSUE THREAD

**Issue by MPi3D** [shamblett/mqtt_client#211]
Hello,

I am working on an app using MQTT with my own Mosquitto broker. The app works on perfectly but would like to add the web support but it produces the following error. What is wrong? Thanks for your helping.

+ Error

```
Error: mqtt-client::NoConnectionException: The maximum allowed connection attempts ({1}) were exceeded. The broker is not responding to the connection request message
(Missing Connection Acknowledgement?
    at Object.throw_ [as throw] (http://localhost:37807/dart_sdk.js:4322:11)
    at mqtt_browser_client.SynchronousMqttBrowserConnectionHandler.new.internalConnect (http://localhost:37807/packages/mqtt_client/mqtt_browser_client.dart.lib.js:114:25)
    at internalConnect.next (<anonymous>)
    at http://localhost:37807/dart_sdk.js:37211:33
    at _RootZone.runUnary (http://localhost:37807/dart_sdk.js:37065:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:37807/dart_sdk.js:32049:29)
    at handleValueCallback (http://localhost:37807/dart_sdk.js:32596:49)
    at Function._propagateToListeners (http://localhost:37807/dart_sdk.js:32634:17)
    at _Future.new.[_completeWithValue] (http://localhost:37807/dart_sdk.js:32477:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:37807/dart_sdk.js:32499:35)
    at Object._microtaskLoop (http://localhost:37807/dart_sdk.js:37326:13)
    at _startMicrotaskLoop (http://localhost:37807/dart_sdk.js:37332:13)
    at http://localhost:37807/dart_sdk.js:32851:9
```

+ Code

``` dart
import "package:mqtt_client/mqtt_browser_client.dart";

void main() async {
  final MqttBrowserClient mqttClient = MqttBrowserClient.withPort(
    "ws://192.168.0.33",
    "Unique_ID",
    8080,
    maxConnectionAttempts: 1,
  );
  await mqttClient.connect();
}
```

+ Mosquitto Configuration

```
listener 8080
protocol websockets
```

+ Version

Mosquitto Version: 1.5.7
Dart Version: 2.9.0-21.10.beta
Mqtt Client Version: 7.3.0

**Comment by shamblett** [comment]
Your code looks OK to me and works OK using the server client and the test mosquito broker.

Please change your host to 'ws://test.mosquitto.org' and try again.

If this works OK its probably your local broker, I'm sure I've read somewhere in the mosquitto docs that the broker supplied from the download page doesn't come with websocket support enabled, you have to do something to enable this.

**Comment by MPi3D** [comment]
Hi,

I tried with the `MqttBrowserClient` class on the test mosquito broker. It works.
I also tried with the `MqttServerClient` class on an Android device with `useWebSocket = true` and it works too.
So I am sure that my Mosquitto broker supports WebSockets.

Thanks for helping again.

**Comment by MPi3D** [comment]
Hi again,

I upgraded Mosquitto from 1.5.7 to 1.6.11 and I resolved the problem. I can connect to my own local broker by using the web now! So I think that the version 1.5.7 of Mosquitto is too old to work.

**Comment by shamblett** [comment]
Thanks for the info, I'll bear this in mind if this issue crops up again for other users.
