### ISSUE TITLE
Error when trying to connect Flutter Web client to EMQ X Broker by WebSocket

### ISSUE THREAD

**Issue by SirJAKfromSpace** [shamblett/mqtt_client#222]
Hello,
I need some help getting my flutter webpage to connect to my EMQ X Broker via WebSocket.
When trying to connect, it fails with the following error:

`mqtt-client::NoConnectionException: The broker is not responding to the connection request message (Missing Connection Acknowledgement?)
`

The MQTTX app is capable of connecting by websocket to my server's broker though somehow. I've attached a screenshot of the config used there to connect.
![InkedAnnotation 2020-09-06 041546_LI](https://user-images.githubusercontent.com/23219242/92314327-f388a280-eff7-11ea-9b17-92f34c5c453c.jpg)

What am I doing wrong? I tried following the example given in `mqtt_client/example/mqtt_browser_client.dart`
Note: I am not using X.XX.XXX.XXX as the IP address, just to be clear.

EMQ X Broker version: 4.1.4
Flutter version: beta, 1.21.0-9.2.pre

**Code**
  
    final client = MqttBrowserClient('ws://X.XX.XXX.XXX', '', maxConnectionAttempts: 0);
    client.port = 8083;
    client.logging(on: true);
    client.onConnected = onConnected;
    client.onDisconnected = onDisconnected;
    client.onSubscribed = onSubscribed;
    client.pongCallback = pong;
    final connMessage = MqttConnectMessage()
        .withClientIdentifier('dash_flutterweb')
        .keepAliveFor(20)
        .startClean()
        .withWillQos(MqttQos.atMostOnce);
    client.connectionMessage = connMessage;
    print('MQTTClient :: Connecting.....');
    try {
      await client.connect();
    } catch (e) {
      print('MQTTClient :: Exception: $e');
      client.disconnect();
    }

**Error:**

Launching lib\main.dart on Chrome in debug mode...
Debug service listening on ws://127.0.0.1:63754/Ihz_hgAZAto=
Connecting to VM Service at ws://127.0.0.1:63754/Ihz_hgAZAto=
MQTTClient :: Connecting.....
2020-09-06 03:39:32.979 -- SynchronousMqttBrowserConnectionHandler::internalConnect entered
2020-09-06 03:39:32.981 -- SynchronousMqttBrowserConnectionHandler::internalConnect - initiating connection try 0
2020-09-06 03:39:32.988 -- MqttBrowserWsConnection::connect -  WS URL is ws://x.xx.xxx.xxx:8083
2020-09-06 03:39:32.998 -- MqttBrowserWsConnection::connect - connection is waiting
2020-09-06 03:39:33.408 -- MqttBrowserWsConnection::connect - websocket has errored
2020-09-06 03:39:33.410 -- SynchronousMqttBrowserConnectionHandler::internalConnect - connection complete
2020-09-06 03:39:33.411 -- SynchronousMqttBrowserConnectionHandler::internalConnect sending connect message
2020-09-06 03:39:33.413 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
Header: MessageType = MqttMessageType.connect, Duplicate = false, Retain = false, Qos = MqttQos.atMostOnce, Size = 0
Connect Variable Header: ProtocolName=MQIsdp, ProtocolVersion=3, ConnectFlags=Connect Flags: Reserved1=false, CleanStart=true, WillFlag=false, WillQos=MqttQos.atMostOnce, WillRetain=false, PasswordFlag=false, UserNameFlag=false, KeepAlive=20
MqttConnectPayload - client identifier is : dash_flutterweb
2020-09-06 03:39:33.422 -- SynchronousMqttBrowserConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
2020-09-06 03:39:38.438 -- SynchronousMqttBrowserConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
2020-09-06 03:39:38.440 -- SynchronousMqttBrowserConnectionHandler::internalConnect failed
MQTTClient :: Exception: mqtt-client::NoConnectionException: The maximum allowed connection attempts ({0}) were exceeded. The broker is not responding to the connection request message (Missing Connection Acknowledgement?
2020-09-06 03:39:38.448 -- SynchronousMqttServerConnectionHandler::disconnect
MQTT :: Disconnected
showToast
{msg: Disconnected, length: short, time: 1, gravity: bottom, bgcolor: 4292030255, textcolor: 4294967295, fontSize: 20, webShowClose: false, webBgColor: linear-gradient(to right, #00b09b, #96c93d), webPosition: right}
null
MQTTClient :: ERROR: Connection status is disconnected with return code of noneSpecified and a disconnection origin of solicited

**Comment by shamblett** [comment]
It looks as though you are connecting to the broker and sending a connect message -
```
020-09-06 03:39:33.410 -- SynchronousMqttBrowserConnectionHandler::internalConnect - connection complete
2020-09-06 03:39:33.411 -- SynchronousMqttBrowserConnectionHandler::internalConnect sending connect message
2020-09-06 03:39:33.413 -- MqttConnectionHandlerBase::sendMessage - MQTTMessage of type MqttMessageType.connect
```
You then wait 5 seconds for the connak message -
```
2020-09-06 03:39:33.422 -- SynchronousMqttBrowserConnectionHandler::internalConnect - pre sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
2020-09-06 03:39:38.438 -- SynchronousMqttBrowserConnectionHandler::internalConnect - post sleep, state = Connection status is connecting with return code of noneSpecified and a disconnection origin of none
```
Which you don't receive, seeing as you have set max connection attempts to 0 the client then gives up.

So the problem is your broker is not sending you a connack message for some reason. Looking at your example and the client code the client id is different for some reason, also the connection parameters in the screenshot have a path of /mqtt set, maybe you have to add this to your URL. You could also try not setting a connect message unless you are sure your broker supports the parameters you have set, I've seen this cause issues before.

The client is doing nothing wrong here and seems to be working as expected, ultimately you will have to look at your broker logs to see why it is not sending you a connack message.

**Comment by Zhiw** [comment]
You can try with:
```
MqttBrowserClient client = MqttBrowserClient.withPort('ws://broker.emqx.io/mqtt', 'ws_client', 8083);
client.websocketProtocols = ["mqttv3.11"];
```

**Comment by SirJAKfromSpace** [comment]
@shamblett and @Zhiw,
Thank you very much for your assistance!

@Zhiw your suggestion fixed it! Thank you!

> You can try with:
> ```
> MqttBrowserClient client = MqttBrowserClient.withPort('ws://broker.emqx.io/mqtt', 'ws_client', 8083);
> client.websocketProtocols = ["mqttv3.11"];
> ```

I will close the issue.

But I am facing a different issue when disconnecting, it says NoSuchMethodFound on line 71 `client.destroy()` in `mqtt_client_mqtt_connection_base.dart`. Any suggestions why this is?

```Exception has occurred.
"Error: NoSuchMethodError: 'destroy'
method not found
Receiver: Instance of 'WebSocket$'
Arguments: []
    at Object.throw_ [as throw] (http://localhost:53054/dart_sdk.js:4334:11)
    at Object.defaultNoSuchMethod (http://localhost:53054/dart_sdk.js:4776:15)
    at WebSocket.noSuchMethod (http://localhost:53054/dart_sdk.js:5827:19)
    at Object.noSuchMethod (http://localhost:53054/dart_sdk.js:4772:30)
    at Object.callMethod (http://localhost:53054/dart_sdk.js:4582:19)
    at Object.dsend (http://localhost:53054/dart_sdk.js:4590:17)
    at mqtt_browser_client.MqttBrowserWsConnection.new.[_disconnect] (http://localhost:53054/packages/mqtt_client/mqtt_client.dart.lib.js:1368:14)
    at mqtt_browser_client.MqttBrowserWsConnection.new.onError (http://localhost:53054/packages/mqtt_client/mqtt_client.dart.lib.js:1353:24)
    at http://localhost:53054/packages/mqtt_client/mqtt_browser_client.dart.lib.js:156:18
    at Object._checkAndCall (http://localhost:53054/dart_sdk.js:4544:16)
    at Object.dcall (http://localhost:53054/dart_sdk.js:4549:17)
    at WebSocket.<anonymous> (http://localhost:53054/dart_sdk.js:105055:21)"
```

screenshot of call stack: 
![image](https://user-images.githubusercontent.com/23219242/92372757-35603880-f11f-11ea-81be-7db0ed6124f9.png)

**Comment by SirJAKfromSpace** [comment]
Also I would like to know why specifying a websocket protocol fixed it?

**Comment by Zhiw** [comment]
> Also I would like to know why specifying a websocket protocol fixed it?

Doc:
```
Some brokers will not accept a list and only expect a single protocol identifier
```

**Comment by SirJAKfromSpace** [comment]
Ah, I see. Noted. Thank you both for your help!

@shamblett, could you please let me know when you push an update to the pub package? Thank you!
