### ISSUE TITLE
Some problems about unsubscribe a durable topic

### ISSUE THREAD

**Issue by TohsakaRin233** [shamblett/mqtt_client#261]
hello,first thx to you for the easy-to-use plugin, but I have some problems when I try to unsubscribe a durable topic
my Client:
```
mqtt_client: ^8.2.0

class Client {
  static MqttServerClient client;
  static String username = "admin";
  static String password = "admin";
  static String server = '192.168.1.5';
  static int port = 1883;
  static String clientIdentifier;//will be set before connect
  static Future<MqttServerClient> connect() async {

    client = MqttServerClient.withPort(server, clientIdentifier, port);
    client.logging(on: false);
    client.autoReconnect = true;
    client.resubscribeOnAutoReconnect = false;
    client.onAutoReconnected = onAutoReconnected;
    client.onConnected = onConnected;
    client.onDisconnected = onDisconnected;
    client.onUnsubscribed = onUnsubscribed;
    client.onSubscribed = onSubscribed;
    client.onSubscribeFail = onSubscribeFail;
    client.pongCallback = pong;

    final connMessage = MqttConnectMessage()
        .authenticateAs(username, password)
        .keepAliveFor(30)
        .withClientIdentifier(clientIdentifier);

    client.connectionMessage = connMessage;

    try {
      await client.connect();
    } catch (e) {
      print('Exception: $e');
      client.disconnect();
    }

    client.updates.listen((List<MqttReceivedMessage<MqttMessage>> c) {
      final MqttPublishMessage message = c[0].payload;
      final payload = MqttPublishPayload.bytesToStringAsString(message.payload.message);
      print('Received message:$payload from topic: ${c[0].topic}>');
      Fluttertoast.showToast(msg: 'Received message:$payload from topic: ${c[0].topic}>',timeInSecForIosWeb: 10);
    });

    return client;
  }
  static void onConnected() {
    print('Connected');
  }
  static void myDisconnect() {
    client.disconnect();
  }
  static void onDisconnected() {
    print('Disconnected');
  }
  static void onAutoReconnected(){
    print("onAutoReconnected");
  }
  static void mySubscribe(String topic) {
    client.subscribe(topic, MqttQos.atLeastOnce);
  }
  static void onSubscribed(String topic) {
    Fluttertoast.showToast(msg: 'Subscribed');
  }
  static void onSubscribeFail(String topic) {
    Fluttertoast.showToast(msg: 'Failed to subscribe $topic');
  }
  static void myUnsubscribe(String topic) {
    client.unsubscribe(topic);
  }
  static void onUnsubscribed(String topic) {
    print("Unsubscribed $topic");
    Fluttertoast.showToast(msg: 'Unsubscribed');
  }
  static void pong() {
    print('Ping response client callback invoked');
  }
```
My ActiveMQ server throw a Exception "Failed to process subscription request" "UNSUBSCRIBE frame not properly formatted, QoS"
my log:
```
org.apache.activemq.transport.mqtt.MQTTProtocolException: Failed to process unsubscribe request
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onUnSubscribe(MQTTProtocolConverter.java:408)
	at org.apache.activemq.transport.mqtt.MQTTProtocolConverter.onMQTTCommand(MQTTProtocolConverter.java:215)
	at org.apache.activemq.transport.mqtt.MQTTTransportFilter.onCommand(MQTTTransportFilter.java:94)
	at org.apache.activemq.transport.TransportSupport.doConsume(TransportSupport.java:83)
	at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:233)
	at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:215)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.Exception: UNSUBSCRIBE frame not properly formatted, QoS
	... 7 more
```
after check the ActiveMQ source code I think the problem maybe caused by the msgHeader，here is the ActiveMQ sourse code:
```
public void onUnSubscribe(UNSUBSCRIBE command) throws MQTTProtocolException {
        checkConnected();
        if (command.qos() != QoS.AT_LEAST_ONCE && (version != V3_1 || publishDollarTopics != true)) {
            throw new MQTTProtocolException("Failed to process unsubscribe request", true, new Exception("UNSUBSCRIBE frame not properly formatted, QoS"));
        }
```
after my Debug I found the msgHeader's MqttQos is atMostOnce and the server may be require atLeastOnce,is it the source that caused my unsubscribe problem? or just I have some wrong settings of my clinet ? Although the problem is solved after I change the Qos from atMostOnce to atLeastOnce 
![image](https://user-images.githubusercontent.com/51444819/112446584-53c01580-8d8b-11eb-9068-12c3e28f9c30.png)
but I don't know if it will cause some other problems, thank you very much.
![image](https://user-images.githubusercontent.com/51444819/112445413-10b17280-8d8a-11eb-9618-6db2c8212e61.png)

**Comment by TohsakaRin233** [comment]
because I'm still using old version dart so I'm not use the 9.0.0 version

**Comment by shamblett** [comment]
Try setting the client  version to 3.1.1 in your setup, the unsubscribe message is different between this and 3.1 -
```
client.setProtocolV311();
```
You should find the client will now set your Qos according to the MQTT v3.1.1 spec.

**Comment by TohsakaRin233** [comment]
Now it's working properly,thank you very much!
