### ISSUE TITLE
connection to the layout renderer failed. this may be caused by a misconfiguration of java

### ISSUE THREAD

**Issue by Lasn-t** [shamblett/mqtt_client#398]
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.net.SocketInputStream.read(SocketInputStream.java:224)
	at mono.android.ListenerThread.run(HostProcessConnection.java:232)

**Comment by Lasn-t** [comment]
can someone help with a way to solve this issue. I'm using visual studio 2019
