### ISSUE TITLE
Disconnected clients do not get properly destroyed

### ISSUE THREAD

**Issue by cbenhagen** [shamblett/mqtt_client#40]
Reconnecting 4 times to a broker results in messages being received 4 times. 

```dart
import 'dart:async';
import 'dart:io';
import 'package:mqtt_client/mqtt_client.dart';

Future<int> main() async {
  MqttClient client;

  void _connect() async {
    client = MqttClient("test.mosquitto.org", "");
    client.logging(false);

    client.onDisconnected = onDisconnected;

    final MqttConnectMessage connMess = MqttConnectMessage()
        .withClientIdentifier("Mqtt_MyClientUniqueId")
        .startClean();
    print("EXAMPLE::Mosquitto client connecting....");
    client.connectionMessage = connMess;

    try {
      await client.connect();
    } catch (e) {
      print("EXAMPLE::client exception - $e");
      client.disconnect();
    }

    if (client.connectionState == ConnectionState.connected) {
      print("EXAMPLE::Mosquitto client connected");
    } else {
      print(
          "EXAMPLE::ERROR Mosquitto client connection failed - disconnecting, state is ${client.connectionState}");
      client.disconnect();
      exit(-1);
    }
  }

  _connect();
  await MqttUtilities.asyncSleep(1);
  print("Disconnecting");
  client.disconnect();
  print("Connection state: ${client.connectionState}");
  // Probably not needed but explicitly allow garbage collection
  client = null;

  await MqttUtilities.asyncSleep(1);

  _connect();
  await MqttUtilities.asyncSleep(1);
  print("Disconnecting");
  client.disconnect();
  print("Connection state: ${client.connectionState}");
  client = null;
  
  await MqttUtilities.asyncSleep(1);

  _connect();
  await MqttUtilities.asyncSleep(1);
  print("Disconnecting");
  client.disconnect();
  print("Connection state: ${client.connectionState}");
  client = null;

  await MqttUtilities.asyncSleep(1);

  _connect();
  await MqttUtilities.asyncSleep(1);
  print("Connection state: ${client.connectionState}");

  client.updates.listen((List<MqttReceivedMessage> c) {
    final MqttPublishMessage recMess = c[0].payload as MqttPublishMessage;
    final String pt =
        MqttPublishPayload.bytesToStringAsString(recMess.payload.message);

    print(
        "EXAMPLE::Change notification:: topic is <${c[0].topic}>, payload is <-- ${pt} -->");
    print("");
  });

  print("EXAMPLE::Publishing our topic");

  final String pubTopic = "Dart/Mqtt_client/testtopic";
  final MqttClientPayloadBuilder builder = MqttClientPayloadBuilder();
  builder.addString("Hello from mqtt_client");

  client.subscribe(pubTopic, MqttQos.exactlyOnce);
  client.publishMessage(pubTopic, MqttQos.exactlyOnce, builder.payload);

  print("EXAMPLE::Sleeping....");
  await MqttUtilities.asyncSleep(120);

  client.disconnect();
  return 0;
}

void onDisconnected() {
  print("EXAMPLE::OnDisconnected client callback - Client disconnection");
  exit(-1);
}
```

```

EXAMPLE::Mosquitto client connecting....
EXAMPLE::Mosquitto client connected
Disconnecting
Connection state: ConnectionState.disconnected
EXAMPLE::Mosquitto client connecting....
EXAMPLE::Mosquitto client connected
Disconnecting
Connection state: ConnectionState.disconnected
EXAMPLE::Mosquitto client connecting....
EXAMPLE::Mosquitto client connected
Disconnecting
Connection state: ConnectionState.disconnected
EXAMPLE::Mosquitto client connecting....
EXAMPLE::Mosquitto client connected
Connection state: ConnectionState.connected
EXAMPLE::Publishing our topic
EXAMPLE::Sleeping....
StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:io/io_sink.dart:160:31)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:165:7)
#2      _Socket.add (dart:io/runtime/binsocket_patch.dart:1607:38)
#3      MqttConnection.send (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection.dart:125:12)
#4      MqttConnectionHandler.sendMessage (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:72:18)
#5      PublishingManager.handlePublish (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/mqtt_client_publishing_manager.dart:139:27)
#6      MqttConnectionHandler.messageAvailable (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:117:13)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#8      CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#13     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _DelayedData.perform (dart:async/stream_impl.dart:584:14)
#18     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
#19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)

StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:io/io_sink.dart:160:31)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:165:7)
#2      _Socket.add (dart:io/runtime/binsocket_patch.dart:1607:38)
#3      MqttConnection.send (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection.dart:125:12)
#4      MqttConnectionHandler.sendMessage (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:72:18)
#5      PublishingManager.handlePublish (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/mqtt_client_publishing_manager.dart:139:27)
#6      MqttConnectionHandler.messageAvailable (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:117:13)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#8      CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#13     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _DelayedData.perform (dart:async/stream_impl.dart:584:14)
#18     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
#19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)

StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:io/io_sink.dart:160:31)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:165:7)
#2      _Socket.add (dart:io/runtime/binsocket_patch.dart:1607:38)
#3      MqttConnection.send (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection.dart:125:12)
#4      MqttConnectionHandler.sendMessage (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:72:18)
#5      PublishingManager.handlePublish (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/mqtt_client_publishing_manager.dart:139:27)
#6      MqttConnectionHandler.messageAvailable (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:117:13)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#8      CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#13     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _DelayedData.perform (dart:async/stream_impl.dart:584:14)
#18     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
#19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)

StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:io/io_sink.dart:160:31)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:165:7)
#2      _Socket.add (dart:io/runtime/binsocket_patch.dart:1607:38)
#3      MqttConnection.send (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection.dart:125:12)
#4      MqttConnectionHandler.sendMessage (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:72:18)
#5      PublishingManager.handlePublishRelease (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/mqtt_client_publishing_manager.dart:162:27)
#6      MqttConnectionHandler.messageAvailable (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:117:13)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#8      CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#13     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _DelayedData.perform (dart:async/stream_impl.dart:584:14)
#18     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
#19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)

StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:io/io_sink.dart:160:31)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:165:7)
#2      _Socket.add (dart:io/runtime/binsocket_patch.dart:1607:38)
#3      MqttConnection.send (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection.dart:125:12)
#4      MqttConnectionHandler.sendMessage (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:72:18)
#5      PublishingManager.handlePublishRelease (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/mqtt_client_publishing_manager.dart:162:27)
#6      MqttConnectionHandler.messageAvailable (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:117:13)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#8      CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#13     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _DelayedData.perform (dart:async/stream_impl.dart:584:14)
#18     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
#19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)

StreamSink is closed and adding to it is an error.
  See http://dartbug.com/29554.
#0      _StreamSinkImpl._reportClosedSink (dart:io/io_sink.dart:160:31)
#1      _StreamSinkImpl.add (dart:io/io_sink.dart:165:7)
#2      _Socket.add (dart:io/runtime/binsocket_patch.dart:1607:38)
#3      MqttConnection.send (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection.dart:125:12)
#4      MqttConnectionHandler.sendMessage (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:72:18)
#5      PublishingManager.handlePublishRelease (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/mqtt_client_publishing_manager.dart:162:27)
#6      MqttConnectionHandler.messageAvailable (file:///Users/ben/.pub-cache/hosted/pub.dartlang.org/mqtt_client-3.3.2/lib/src/connectionhandling/mqtt_client_mqtt_connection_handler.dart:117:13)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#8      CastStreamSubscription._onData (dart:_internal/async_cast.dart:81:11)
#9      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#10     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#11     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#12     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
#13     _WhereStream._handleData (dart:async/stream_pipe.dart:207:12)
#14     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _DelayedData.perform (dart:async/stream_impl.dart:584:14)
#18     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:700:11)
#19     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:660:7)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#22     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:113:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:166:5)

EXAMPLE::Change notification:: topic is <Dart/Mqtt_client/testtopic>, payload is <-- Hello from mqtt_client -->

EXAMPLE::Change notification:: topic is <Dart/Mqtt_client/testtopic>, payload is <-- Hello from mqtt_client -->

EXAMPLE::Change notification:: topic is <Dart/Mqtt_client/testtopic>, payload is <-- Hello from mqtt_client -->

EXAMPLE::Change notification:: topic is <Dart/Mqtt_client/testtopic>, payload is <-- Hello from mqtt_client -->

```

**Comment by lxzxl** [comment]
Same problem when trying the flutter example.

**Comment by shamblett** [comment]
Believe fixed.
