### ISSUE TITLE
Can't get basic example working

### ISSUE THREAD

**Issue by lukepighetti** [shamblett/mqtt_client#421]
I am running mosquitto. Every mqtt client I have used worked with nothing more than `mqtt://imac.local` as the server and no other configuration

```dart
import 'package:mqtt_client/mqtt_client.dart';
import 'package:mqtt_client/mqtt_server_client.dart';

Future<void> main(List<String> arguments) async {
  final client = MqttServerClient.withPort("imac.local", "pid_dart", 1883);
  client.setProtocolV311();
  final connectionMessage =
      MqttConnectMessage().withClientIdentifier('SJH_client');
  client.connectionMessage = connectionMessage;
  await client.connect();
  client.subscribe("*", MqttQos.atMostOnce);

  await for (final messages in client.updates!) {
    for (final message in messages) {
      print("${message.topic} ${message.payload}");
    }
  }
}
```

This fails with `MqttConnectReturnCode.identifierRejected`

```
Unhandled exception:
mqtt-client::NoConnectionException: The maximum allowed connection attempts ({3}) were exceeded. The broker is not responding to the connection request message correctly The return code is MqttConnectReturnCode.identifierRejected
#0      SynchronousMqttServerConnectionHandler.internalConnect (package:mqtt_client/src/connectionhandling/server/mqtt_client_synchronous_mqtt_server_connection_handler.dart:125:11)
<asynchronous suspension>
#1      MqttConnectionHandlerBase.connect (package:mqtt_client/src/connectionhandling/mqtt_client_mqtt_connection_handler_base.dart:100:7)
<asynchronous suspension>
#2      MqttServerClient.connect (package:mqtt_client/src/mqtt_server_client.dart:95:12)
<asynchronous suspension>
#3      main (file:///private/tmp/pid/bin/pid.dart:10:3)
<asynchronous suspension>
```

**Comment by lukepighetti** [comment]
Here's my minimal working example:

```dart
import 'dart:io';

import 'package:mqtt_client/mqtt_client.dart';
import 'package:mqtt_client/mqtt_server_client.dart';

Future<void> main(List<String> arguments) async {
  final client = MqttServerClient('imac.local', '');
  client.setProtocolV311();
  client.keepAlivePeriod = 30;
  await client.connect();
  client.subscribe('#', MqttQos.atMostOnce);

  await for (final batch in client.updates!) {
    for (final message in batch) {
      final p = message.payload;
      if (p is! MqttPublishMessage) continue;
      final pt = MqttPublishPayload.bytesToStringAsString(p.payload.message);
      print('<${message.topic}>: $pt');
    }
  }
}
```
